spring.application.name=catalog-service
spring.jpa.open-in-view=false
server.port=${APP_PORT:8081}
server.shutdown=graceful

management.endpoints.web.exposure.include=health,info
management.info.git.mode=full

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:15432/catalog_db}
spring.datasource.username=${DB_USER:sujay}
spring.datasource.password=${DB_PASSWORD:password}


