name: bookstore-microservices
services:
  catalog-db:
    image: postgres:16-alpine
    container_name: catalog-db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
      - ./catalog_db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 800m

volumes:
  catalog_db_data:
