name: Catalog Service

on:
  push:
    branches: [main]
    paths:
      - catalog-service/**
  pull_request:
    paths:
      - catalog-service/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./catalog-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build catalog-service
        run: ./mvnw -ntp -pl catalog-service -am verify